apiVersion: v1
kind: Pod
metadata:
   name: confluent-client
spec:
   containers:
   - name: confluent-client
     image: confluentinc/cp-kafka:5.0.0
     command:
       - sh
       - -c
       - "exec tail -f /dev/null"
